import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Dashboard from '../components/Dashboard'
import Loader from '../components/Loader'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter();
  const { status,data: session }= useSession({
    required:true,
    onUnauthenticated() {
      router.push("/auth/signin")
    }

  });

  if(status==="loading") {
    return      <div className='flex items-center justify-center'>
      <Loader />

   </div>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </div>
  )
}

export default Home
